language: node_js
node_js:
  - "8.10"
cache:
  directories:
  - node_modules
before_install:
  - echo $TRAVIS_REPO_SLUG
  - git clone https://github.com/vutsalsinghal/vutsalsinghal.github.io.git .
  - git checkout code
  - git pull
install:
  - npm install
script:
  - sh push.sh
branches:
  only:
  - master
  