language: node_js
node_js:
  - "8.10"
cache:
  directories:
  - node_modules
install:
  - npm install
script:
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  target-branch: master
  verbose: true
  keep-history: true
after_success:
  - sh push.sh
on:
  branch: master