version: 2
jobs:
  site-deploy:
    docker:
      - image: circleci/node:8.10
    steps:
      - restore_cache:
          keys:
            - source-v1-{{ .Branch }}
            - source-v1-
      - checkout
      - run:
          name: Install node dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm run test
      - run:
          name: Install pip
          command: sudo apt-get install python-pip python-dev
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Deploy to S3
          command: npm run deploy
      - save_cache:
          key: source-v1-{{ .Branch }}
          paths:
            - ".git"

workflows:
  version: 2
  build:
    jobs:
      - site-deploy:
          filters:
            branches:
              only: code