version: 2
jobs:
  site-deploy:
    docker:
      - image: node:8.10
    steps:
      - restore_cache:
          keys:
            - source-v1-{{ .Branch }}
            - source-v1-
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm run test
      - run:
         name: Building React site
         command: npm run build
      - run:
          name: Install and configure dependencies
          command: |
            sudo apt-get -y -qq install awscli
            npm install -g --silent gh-pages
            git config user.email "vutsalsinghal@gmail.com"
            git config user.name "vutsalsinghal"
            cp Readme.md LICENSE .gitignore build
      - add_ssh_keys:
          fingerprints:
            - "a9:ee:a1:01:e3:fd:60:b2:fe:ab:63:e3:2b:74:59:ff"
      - run:
          name: Deploy to gh-pages
          command: gh-pages --dist build --branch master --message "[skip ci] Updated build files"
      - run:
          name: Deploy to S3
          command: npm run deploy
      - save_cache:
          key: source-v1-{{ .Branch }}
          paths:
            - ".git"

workflows:
  version: 2
  build:
    jobs:
      - site-deploy:
          filters:
            branches:
              only: code