version: 2
jobs: 
  build:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - run: npm install
      - run: npm run build
  deploy:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - attach_workspace:
          at: build
      - run:
        name: Install and configure dependencies
        command: |
          npm install -g --silent gh-pages
          git config user.email "vutsalsinghal@gmail.com"
          git config user.name "vutsalsinghal"
      - add_ssh_keys:
          fingerprints:
            - "a9:ee:a1:01:e3:fd:60:b2:fe:ab:63:e3:2b:74:59:ff"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dist build --branch master

workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy:
        requires: 
          - build
        filters:
          branches:
            only: code